2019-02-08 16:31:28 database: wrong user or password; user: "ROOT"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:155)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 9 more
2019-02-08 16:32:45 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: User "ADMIN" not found; SQL statement:
ALTER USER admin SET PASSWORD 'alpine' [90032-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Database.getUser(Database.java:1174)
	at org.h2.command.Parser.parseAlterUser(Parser.java:5499)
	at org.h2.command.Parser.parseAlter(Parser.java:5375)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-02-08 16:33:35 database: wrong user or password; user: "ROOT"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:33:38 database: wrong user or password; user: "SA"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.test(WebApp.java:892)
	at org.h2.server.web.WebApp.process(WebApp.java:221)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:33:47 database: wrong user or password; user: "ROOT"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.test(WebApp.java:892)
	at org.h2.server.web.WebApp.process(WebApp.java:221)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:33:55 database: wrong user or password; user: "ADMIN"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:34:06 database: wrong user or password; user: "SA"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:34:10 database: wrong user or password; user: "SA"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:34:10 database: wrong user or password; user: "SA"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:35:10 database: wrong user or password; user: "SA"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.test(WebApp.java:892)
	at org.h2.server.web.WebApp.process(WebApp.java:221)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:35:14 database: wrong user or password; user: "SA"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.test(WebApp.java:892)
	at org.h2.server.web.WebApp.process(WebApp.java:221)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:35:23 database: wrong user or password; user: "ROOT"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.test(WebApp.java:892)
	at org.h2.server.web.WebApp.process(WebApp.java:221)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:35:37 database: wrong user or password; user: "SA"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.test(WebApp.java:892)
	at org.h2.server.web.WebApp.process(WebApp.java:221)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:36:25 database: wrong user or password; user: "ROOT"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:36:59 database: wrong user or password; user: "ADMIN"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:37:03 database: wrong user or password; user: "ADMIN"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:37:06 database: wrong user or password; user: "SA"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:41:04 database: wrong user or password; user: "SA"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:41:06 database: wrong user or password; user: "SA"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.test(WebApp.java:892)
	at org.h2.server.web.WebApp.process(WebApp.java:221)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-08 16:41:24 database: wrong user or password; user: "SA"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:155)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 9 more
2019-02-08 16:42:08 database: wrong user or password; user: "SA"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:155)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 9 more
2019-02-08 16:43:04 database: wrong user or password; user: "SA"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:155)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 9 more
2019-02-08 16:44:23 database: wrong user or password; user: ""ROOT""
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:155)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 9 more
2019-02-08 16:44:28 database: wrong user or password; user: "ROOT"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:155)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 9 more
2019-02-08 16:57:34 database: wrong user or password; user: "SA"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:155)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 9 more
2019-02-08 17:03:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: User "SA" not found; SQL statement:
ALTER USER sa SET PASSWORD alpine [90032-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Database.getUser(Database.java:1174)
	at org.h2.command.Parser.parseAlterUser(Parser.java:5499)
	at org.h2.command.Parser.parseAlter(Parser.java:5375)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-02-08 17:03:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: User "SA" not found; SQL statement:
ALTER USER sa SET PASSWORD 'alpine' [90032-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.Database.getUser(Database.java:1174)
	at org.h2.command.Parser.parseAlterUser(Parser.java:5499)
	at org.h2.command.Parser.parseAlter(Parser.java:5375)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-02-14 14:07:56 jdbc[6]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:197)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:137)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 14 more
2019-02-14 14:10:23 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Column "TESTSCHEMA" not found; SQL statement:
select testschema [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.command.dml.Select.prepare(Select.java:858)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-02-14 14:10:28 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE JOB ADD CONSTRAINT FKJOB594400 FOREIGN KEY ()[*] REFERENCES MECHANIC () "; expected "identifier"; SQL statement:
ALTER TABLE Job ADD CONSTRAINT FKJob594400 FOREIGN KEY () REFERENCES Mechanic () [42001-197]
2019-02-14 14:10:29 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE ""User"" ADD CONSTRAINT FKUSER762139 FOREIGN KEY ()[*] REFERENCES ADMIN () "; expected "identifier"; SQL statement:
ALTER TABLE "User" ADD CONSTRAINT FKUser762139 FOREIGN KEY () REFERENCES Admin () [42001-197]
2019-02-14 14:14:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP ADMIN[*]
DROP CAR
DROP CUSTOMER "; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE, SYNONYM"; SQL statement:
Drop ADMIN
Drop CAR
Drop CUSTOMER [42001-197]
2019-02-14 14:14:55 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP TABLE ADMIN, CAR, CUSTOMER, JOB, MANUFACTURER, MECHANIC , ORDER_PART , ORDER[*], PART, PAYMENT, REPORT, TASK, USER "; expected "identifier"; SQL statement:
DROP TABLE ADMIN, CAR, CUSTOMER, JOB, MANUFACTURER, MECHANIC , ORDER_PART , Order, PART, PAYMENT, REPORT, TASK, User [42001-197]
2019-02-14 14:15:40 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP TABLE ORDER[*] "; expected "identifier"; SQL statement:
drop table order [42001-197]
2019-02-14 14:16:01 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP TABLE ORDER[*] "; expected "identifier"; SQL statement:
drop table order [42001-197]
2019-02-14 14:16:07 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP TABLE ORDER[*] "; expected "identifier"; SQL statement:
drop table Order [42001-197]
2019-02-14 14:16:16 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP TABLE ORDER[*] "; expected "identifier"; SQL statement:
drop table Order [42001-197]
2019-02-14 14:16:40 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "USER" not found; SQL statement:
drop table User [42102-197]
2019-02-14 14:20:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "ADMIN" already exists; SQL statement:
CREATE TABLE GARAGE.Admin (Username int, Password int, Name int, "Column" int) [42101-197]
2019-02-14 14:20:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "JOB" not found; SQL statement:
ALTER TABLE Job ADD CONSTRAINT FKJob418395 FOREIGN KEY (Username) REFERENCES "User" (Username) [42102-197]
2019-02-14 14:20:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "CAR" not found; SQL statement:
ALTER TABLE Car ADD CONSTRAINT FKCar448763 FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID) [42102-197]
2019-02-14 14:20:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "JOB" not found; SQL statement:
ALTER TABLE Job ADD CONSTRAINT FKJob455908 FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID) [42102-197]
2019-02-14 14:20:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "Order" not found; SQL statement:
ALTER TABLE "Order" ADD CONSTRAINT FKOrder39294 FOREIGN KEY (Username) REFERENCES "User" (Username) [42102-197]
2019-02-14 14:20:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "PART" not found; SQL statement:
ALTER TABLE Part ADD CONSTRAINT FKPart521343 FOREIGN KEY (ManufacturerID) REFERENCES Manufacturer (ManufacturerID) [42102-197]
2019-02-14 14:20:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "ORDER_PART" not found; SQL statement:
ALTER TABLE Order_part ADD CONSTRAINT FKOrder_part680645 FOREIGN KEY (OrderID) REFERENCES "Order" (OrderID) [42102-197]
2019-02-14 14:20:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "ORDER_PART" not found; SQL statement:
ALTER TABLE Order_part ADD CONSTRAINT FKOrder_part678605 FOREIGN KEY (Part_ID) REFERENCES Part (Part_ID) [42102-197]
2019-02-14 14:20:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "JOB" not found; SQL statement:
ALTER TABLE Job ADD CONSTRAINT FKJob497645 FOREIGN KEY (Task_ID) REFERENCES Task (Task_ID) [42102-197]
2019-02-14 14:20:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "JOB" not found; SQL statement:
ALTER TABLE Job ADD CONSTRAINT FKJob399256 FOREIGN KEY (CarRegistrationID) REFERENCES Car (RegistrationID) [42102-197]
2019-02-14 14:20:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE JOB ADD CONSTRAINT FKJOB594400 FOREIGN KEY ()[*] REFERENCES MECHANIC () "; expected "identifier"; SQL statement:
ALTER TABLE Job ADD CONSTRAINT FKJob594400 FOREIGN KEY () REFERENCES Mechanic () [42001-197]
2019-02-14 14:20:03 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE ""User"" ADD CONSTRAINT FKUSER762139 FOREIGN KEY ()[*] REFERENCES ADMIN () "; expected "identifier"; SQL statement:
ALTER TABLE "User" ADD CONSTRAINT FKUser762139 FOREIGN KEY () REFERENCES Admin () [42001-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "ADMIN" already exists; SQL statement:
CREATE TABLE GARAGE.Admin (Username int, Password int, Name int, "Column" int) [42101-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "CAR" already exists; SQL statement:
CREATE TABLE GARAGE.Car (RegistrationID int GENERATED BY DEFAULT AS IDENTITY, CustomerID int NOT NULL, JobID int NOT NULL, Make char(20), Model varchar(25), EngSerial int, ChassisNumber int, Colour char(15), PRIMARY KEY (RegistrationID)) [42101-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "CUSTOMER" already exists; SQL statement:
CREATE TABLE GARAGE.Customer (CustomerID int GENERATED BY DEFAULT AS IDENTITY, FirstName char(25), LastName char(25), Type char(10), Adress varchar(40), Phone int, Email varchar(30), Car int, PRIMARY KEY (CustomerID)) [42101-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "JOB" already exists; SQL statement:
CREATE TABLE GARAGE.Job (JobID int GENERATED BY DEFAULT AS IDENTITY, Username varchar(20), CustomerID int, Task_ID int, CarRegistrationID int NOT NULL, DateBookedIn date, Phone int, Description varchar(255), SparePartsUsed varchar(100), Status char(20), PRIMARY KEY (JobID)) [42101-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "MANUFACTURER" already exists; SQL statement:
CREATE TABLE GARAGE.Manufacturer (ManufacturerID int GENERATED BY DEFAULT AS IDENTITY, CompanyName varchar(30), CompanyAdress varchar(30), Phone int, Fax int, PRIMARY KEY (ManufacturerID)) [42101-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "MECHANIC" already exists; SQL statement:
CREATE TABLE GARAGE.Mechanic (Username int, HourlyRate int) [42101-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "Order" already exists; SQL statement:
CREATE TABLE GARAGE."Order" (OrderID int GENERATED BY DEFAULT AS IDENTITY, Username varchar(20) NOT NULL, Description int, Items int, PRIMARY KEY (OrderID)) [42101-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "ORDER_PART" already exists; SQL statement:
CREATE TABLE GARAGE.Order_part (OrderID int NOT NULL, Part_ID int NOT NULL, StockItem int, OrderQty int, Value int, PRIMARY KEY (OrderID, Part_ID)) [42101-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "PART" already exists; SQL statement:
CREATE TABLE GARAGE.Part (Part_ID int GENERATED BY DEFAULT AS IDENTITY, ManufacturerID int NOT NULL, Name varchar(35), VehicleType char(20), Year int, Price float, Stock_level int, PRIMARY KEY (Part_ID)) [42101-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "PAYMENT" already exists; SQL statement:
CREATE TABLE GARAGE.Payment (Type int, PaymentID int, "Date" int) [42101-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "JOB" not found; SQL statement:
ALTER TABLE Job ADD CONSTRAINT FKJob418395 FOREIGN KEY (Username) REFERENCES "User" (Username) [42102-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "CAR" not found; SQL statement:
ALTER TABLE Car ADD CONSTRAINT FKCar448763 FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID) [42102-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "JOB" not found; SQL statement:
ALTER TABLE Job ADD CONSTRAINT FKJob455908 FOREIGN KEY (CustomerID) REFERENCES Customer (CustomerID) [42102-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "Order" not found; SQL statement:
ALTER TABLE "Order" ADD CONSTRAINT FKOrder39294 FOREIGN KEY (Username) REFERENCES "User" (Username) [42102-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "PART" not found; SQL statement:
ALTER TABLE Part ADD CONSTRAINT FKPart521343 FOREIGN KEY (ManufacturerID) REFERENCES Manufacturer (ManufacturerID) [42102-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "ORDER_PART" not found; SQL statement:
ALTER TABLE Order_part ADD CONSTRAINT FKOrder_part680645 FOREIGN KEY (OrderID) REFERENCES "Order" (OrderID) [42102-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "ORDER_PART" not found; SQL statement:
ALTER TABLE Order_part ADD CONSTRAINT FKOrder_part678605 FOREIGN KEY (Part_ID) REFERENCES Part (Part_ID) [42102-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "JOB" not found; SQL statement:
ALTER TABLE Job ADD CONSTRAINT FKJob497645 FOREIGN KEY (Task_ID) REFERENCES Task (Task_ID) [42102-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "JOB" not found; SQL statement:
ALTER TABLE Job ADD CONSTRAINT FKJob399256 FOREIGN KEY (CarRegistrationID) REFERENCES Car (RegistrationID) [42102-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE JOB ADD CONSTRAINT FKJOB594400 FOREIGN KEY ()[*] REFERENCES MECHANIC () "; expected "identifier"; SQL statement:
ALTER TABLE Job ADD CONSTRAINT FKJob594400 FOREIGN KEY () REFERENCES Mechanic () [42001-197]
2019-02-14 14:21:04 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE ""GARAGE.User"" ADD CONSTRAINT FKUSER762139 FOREIGN KEY ()[*] REFERENCES ADMIN () "; expected "identifier"; SQL statement:
ALTER TABLE "GARAGE.User" ADD CONSTRAINT FKUser762139 FOREIGN KEY () REFERENCES Admin () [42001-197]
2019-02-14 14:22:14 jdbc[6]: exception
org.h2.jdbc.JdbcSQLException: Table "user" not found; SQL statement:
drop table "user" [42102-197]
2019-02-14 14:22:35 database: wrong user or password; user: "ROOT"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-02-17 20:35:33 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "USER" not found; SQL statement:
select * from GARAGE.USER [42102-197]
2019-02-17 20:35:38 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "USER" not found; SQL statement:
select * from GARAGE.User [42102-197]
2019-02-17 20:36:24 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * GARAGE[*].ADMIN "; SQL statement:
select * GARAGE.ADMIN [42000-197]
2019-02-17 20:37:38 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.ADMIN DROP COLUMN [*]"; expected "identifier"; SQL statement:
ALTER TABLE GARAGE.ADMIN drop Column [42001-197]
2019-02-17 20:38:26 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.ADMIN DROP 'Column'[*]"; expected "identifier"; SQL statement:
ALTER TABLE GARAGE.ADMIN DROP 'Column' [42001-197]
2019-02-17 20:38:54 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Column "COLUMN" not found; SQL statement:
ALTER TABLE GARAGE.ADMIN DROP COLUMN Column [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6088)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-02-17 20:38:58 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.ADMIN DROP COLUMN 'Column'[*]"; expected "identifier"; SQL statement:
ALTER TABLE GARAGE.ADMIN DROP COLUMN 'Column' [42001-197]
2019-02-17 20:39:14 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "ADMIN" not found; SQL statement:
select * from ADMIN [42102-197]
2019-02-17 20:39:56 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Column "Admin" not found; SQL statement:
insert into GARAGE.ADMIN ("Admin", "arawin", "Arawin") [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.parseColumn(Parser.java:936)
	at org.h2.command.Parser.parseColumnList(Parser.java:920)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1258)
	at org.h2.command.Parser.parseInsert(Parser.java:1222)
	at org.h2.command.Parser.parsePrepared(Parser.java:431)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-02-17 20:40:07 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "TABLE" not found; SQL statement:
insert into TABLE GARAGE.ADMIN ("Admin", "arawin", "Arawin") [42102-197]
2019-02-17 20:41:18 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'Admin' (ADMIN: USERNAME INT)"; SQL statement:
insert into GARAGE.ADMIN (USERNAME, PASSWORD, NAME)
Values ('Admin', 'arawin', 'Arawin') -- ('Admin', 'arawin', 'Arawin') [22018-197]
2019-02-17 20:41:49 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Column "Admin" not found; SQL statement:
insert into GARAGE.ADMIN (USERNAME, PASSWORD, NAME)
Values ("Admin", "arawin", "Arawin") [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.command.dml.Insert.prepare(Insert.java:314)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-02-17 20:42:36 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Column "Admin" not found; SQL statement:
insert into GARAGE.ADMIN 
Values ("Admin", "arawin", "Arawin") [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.command.dml.Insert.prepare(Insert.java:314)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-02-17 20:42:51 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Column "Admin" not found; SQL statement:
INSERT INTO  GARAGE.ADMIN 
Values ("Admin", "arawin", "Arawin") [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.command.dml.Insert.prepare(Insert.java:314)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-02-17 20:43:03 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'Admin' (ADMIN: USERNAME INT)"; SQL statement:
INSERT INTO  GARAGE.ADMIN 
Values ('Admin', 'arawin', 'Arawin') -- ('Admin', 'arawin', 'Arawin') [22018-197]
2019-02-17 20:45:08 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'Admin' (ADMIN: USERNAME INT)"; SQL statement:
INSERT INTO GARAGE.ADMIN VALUES ('Admin', 'arawin', 'ARAWIN') -- ('Admin', 'arawin', 'ARAWIN') [22018-197]
2019-02-17 20:47:28 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Column "ADMIN" not found; SQL statement:
ALTER TABLE GARAGE.ADMIN 
ALTER COLUMN ADMIN VARCHAR [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.columnIfTableExists(Parser.java:6283)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6159)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-02-18 21:35:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO GARAGE.ADMIN VALUES (""Jimin"", ""nojams"", [*]""Jimin);"; SQL statement:
INSERT INTO GARAGE.ADMIN VALUES ("Jimin", "nojams", "Jimin); [42000-197]
2019-02-18 21:36:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "Jimin" not found; SQL statement:
INSERT INTO GARAGE.ADMIN VALUES ("Jimin", "nojams", "Jimin") [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.command.dml.Insert.prepare(Insert.java:314)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-02-18 21:36:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "Jimin" not found; SQL statement:
INSERT INTO GARAGE.ADMIN 
VALUES ("Jimin", "nojams", "Jimin") [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.command.dml.Insert.prepare(Insert.java:314)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:844)
2019-02-20 16:20:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.""User"" USER[*]"; expected "ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
ALTER TABLE GARAGE."User" USER [42001-197]
2019-02-20 16:22:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USER" not found; SQL statement:
select * from USER [42102-197]
2019-03-04 20:12:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USER" not found; SQL statement:
select * from USER [42102-197]
2019-03-04 20:17:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO GARAGE.USER ('Kaneki'[*], 'haise', 'Kaneki', 'Ken', 'FRANCHISEE') "; expected "identifier"; SQL statement:
insert into GARAGE.USER ('Kaneki', 'haise', 'Kaneki', 'Ken', 'FRANCHISEE') [42001-197]
2019-03-04 20:17:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "Kaneki" not found; SQL statement:
insert into GARAGE.USER ("Kaneki", "haise", "Kaneki", "Ken", "FRANCHISEE") [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.parseColumn(Parser.java:936)
	at org.h2.command.Parser.parseColumnList(Parser.java:920)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1258)
	at org.h2.command.Parser.parseInsert(Parser.java:1222)
	at org.h2.command.Parser.parsePrepared(Parser.java:431)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-07 14:52:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "JAVA[*] ORG.H2.TOOLS.SCRIPT -URL JDBC:H2:~/TEST -USER SA -SCRIPT TEST.ZIP -OPTIONS COMPRESSION ZIP "; SQL statement:
java org.h2.tools.Script -url jdbc:h2:~/test -user sa -script test.zip -options compression zip [42000-197]
2019-03-07 14:52:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ORG[*].H2.TOOLS.SCRIPT -URL JDBC:H2:~/TEST -USER SA -SCRIPT TEST.ZIP -OPTIONS COMPRESSION ZIP "; SQL statement:
org.h2.tools.Script -url jdbc:h2:~/test -user sa -script test.zip -options compression zip [42000-197]
2019-03-07 14:53:28 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException"; SQL statement:
backup to backuptest.zip [50000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:307)
	at org.h2.command.Command.executeUpdate(Command.java:274)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at org.h2.expression.ExpressionColumn.getValue(ExpressionColumn.java:179)
	at org.h2.command.dml.BackupCommand.update(BackupCommand.java:49)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	... 9 more
2019-03-15 15:17:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "["; SQL statement:
ALTER TABLE GARAGE.CUSTOMER CHANGE ADRESS ADDRESS [VARCHAR] [50004-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4400)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4215)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6116)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-15 15:24:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: ; SQL statement:
ALTER TABLE GARAGE.CAR CHANGE REGISTRATIONID REGISTRATION_ID [50004-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4400)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4215)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6116)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-15 15:37:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.USER ([*]FIRST NAME) FIRSTNAME VARCHAR "; expected "ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
ALTER TABLE GARAGE.USER (First Name) FIRSTNAME VARCHAR [42001-197]
2019-03-15 15:38:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.USER CHANGE ([*]FIRST NAME) FIRSTNAME VARCHAR "; expected "identifier"; SQL statement:
ALTER TABLE GARAGE.USER CHANGE (First Name) FIRSTNAME VARCHAR [42001-197]
2019-03-15 15:38:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "FIRST" not found; SQL statement:
ALTER TABLE GARAGE.USER CHANGE First Name FIRSTNAME VARCHAR [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.columnIfTableExists(Parser.java:6283)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6112)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-15 15:38:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "FIRSTNAME" not found; SQL statement:
ALTER TABLE GARAGE.USER CHANGE FirstName FIRSTNAME VARCHAR [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.columnIfTableExists(Parser.java:6283)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6112)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-15 15:38:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.USER CHANGE FIRST[*]\NAME FIRSTNAME VARCHAR "; SQL statement:
ALTER TABLE GARAGE.USER CHANGE First\Name FIRSTNAME VARCHAR [42000-197]
2019-03-15 16:09:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP GARAGE[*]"; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE, SYNONYM"; SQL statement:
DROP GARAGE [42001-197]
2019-03-15 16:10:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot drop "GARAGE" because "Order, PAYMENT, TASK, ORDER_PART, REPORT, MANUFACTURER, USER, REG, CAR, MECHANIC, PART, CUSTOMER, JOB, SYSTEM_SEQUENCE_15D60306_67A0_4E46_9E39_34EF0E2D403E, SYSTEM_SEQUENCE_48537604_3CB4_48DD_BD2B_473726FECDD1, SYSTEM_SEQUENCE_03BC6F1E_B320_413C_8E86_4C747C1039D2, SYSTEM_SEQUENCE_4F23E837_EBE6_468A_82C5_09FAB9D0D511, SYSTEM_SEQUENCE_46DD4187_58C8_4F5D_9B27_2450DFA000FF, SYSTEM_SEQUENCE_9523AEF1_0B86_455C_9FB7_1B3A7B296EF7, SYSTEM_SEQUENCE_83858D62_1D4A_49C5_838B_262163C2757A, SYSTEM_SEQUENCE_B712B25E_9E39_421C_8DEA_501E80CECD22, PRIMARY_KEY_1, PRIMARY_KEY_2, PRIMARY_KEY_4, PRIMARY_KEY_10, PRIMARY_KEY_5, PRIMARY_KEY_11, PRIMARY_KEY_8, FKREPORT822311_INDEX_8, PRIMARY_KEY_14, PRIMARY_KEY_27, PRIMARY_KEY_28, PRIMARY_KEY_4B, CONSTRAINT_28, CONSTRAINT_10, CONSTRAINT_2, CONSTRAINT_4, CONSTRAINT_5, CONSTRAINT_11, CONSTRAINT_14, FKREPORT822311, CONSTRAINT_8, CONSTRAINT_27, CONSTRAINT_1, CONSTRAINT_4B" depends on it; SQL statement:
DROP SCHEMA GARAGE [90107-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.command.ddl.DropSchema.update(DropSchema.java:59)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-15 16:10:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "USER" not found; SQL statement:
DROP TABLE USER [42102-197]
2019-03-15 16:10:25 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "GARAGE" not found; SQL statement:
DROP TABLE GARAGE [42102-197]
2019-03-15 16:10:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "REPORTS" not found; SQL statement:
DROP TABLE GARAGE.REPORTS [42102-197]
2019-03-15 16:11:09 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "MECHANIC" not found; SQL statement:
DROP TABLE GARAGE.MANUFACTURER,MECHANIC,REG [42102-197]
2019-03-15 16:11:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP TABLE GARAGE.ORDER[*]"; expected "identifier"; SQL statement:
DROP TABLE GARAGE.ORDER [42001-197]
2019-03-15 16:11:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP TABLE GARAGE.ORDER[*] "; expected "identifier"; SQL statement:
DROP TABLE GARAGE.Order [42001-197]
2019-03-15 16:11:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP TABLE GARAGE.ORDER[*] "; expected "identifier"; SQL statement:
DROP TABLE GARAGE.Order [42001-197]
2019-03-15 16:14:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP TABLE CUSTOMER, INVOICE, JOB, JOB_TASK, MANUFACTURER ,[*]"; expected "identifier"; SQL statement:
DROP TABLE CUSTOMER, INVOICE, JOB, JOB_TASK, MANUFACTURER , [42001-197]
2019-03-15 16:18:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "User" not found; SQL statement:
ALTER TABLE Job ADD CONSTRAINT FKJob418395 FOREIGN KEY (Username) REFERENCES "User" (Username) [42102-197]
2019-03-15 16:18:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "Order" not found; SQL statement:
ALTER TABLE "Order" ADD CONSTRAINT FKOrder39294 FOREIGN KEY (Username) REFERENCES "User" (Username) [42102-197]
2019-03-15 16:18:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "Order" not found; SQL statement:
ALTER TABLE Order_part ADD CONSTRAINT FKOrder_part680645 FOREIGN KEY (OrderID) REFERENCES "Order" (OrderID) [42102-197]
2019-03-15 16:18:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "User" not found; SQL statement:
ALTER TABLE Report ADD CONSTRAINT FKReport822311 FOREIGN KEY (Username) REFERENCES "User" (Username) [42102-197]
2019-03-15 16:18:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "User" not found; SQL statement:
ALTER TABLE "User" ADD CONSTRAINT FKUser113117 FOREIGN KEY (AdminUsername) REFERENCES Admin (Username) [42102-197]
2019-03-15 16:18:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "User" not found; SQL statement:
ALTER TABLE Mechanic ADD CONSTRAINT FKMechanic162102 FOREIGN KEY (Username) REFERENCES "User" (Username) [42102-197]
2019-03-15 16:18:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "Backup" not found; SQL statement:
ALTER TABLE "Backup" ADD CONSTRAINT FKBackup404245 FOREIGN KEY (AdminUsername) REFERENCES Admin (Username) [42102-197]
2019-03-15 16:18:55 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP *[*]"; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE, SYNONYM"; SQL statement:
DROP * [42001-197]
2019-03-15 16:19:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP TABLE *[*]"; expected "identifier"; SQL statement:
DROP TABLE * [42001-197]
2019-03-15 16:19:04 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP *[*] TABLE"; expected "TABLE, INDEX, USER, SEQUENCE, CONSTANT, TRIGGER, VIEW, ROLE, ALIAS, SCHEMA, ALL, DOMAIN, TYPE, DATATYPE, AGGREGATE, SYNONYM"; SQL statement:
DROP * TABLE [42001-197]
2019-03-15 16:19:21 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DROP ALL[*]"; expected "OBJECTS"; SQL statement:
DROP ALL [42001-197]
2019-03-15 16:20:45 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "User" not found; SQL statement:
ALTER TABLE Job ADD CONSTRAINT FKJob418395 FOREIGN KEY (Username) REFERENCES "User" (Username) [42102-197]
2019-03-15 16:20:45 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE ORDER[*] ADD CONSTRAINT FKORDER39294 FOREIGN KEY (USERNAME) REFERENCES ""User"" (USERNAME) "; expected "identifier"; SQL statement:
ALTER TABLE ORDER ADD CONSTRAINT FKOrder39294 FOREIGN KEY (Username) REFERENCES "User" (Username) [42001-197]
2019-03-15 16:20:45 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "Order" not found; SQL statement:
ALTER TABLE ORDER_PART ADD CONSTRAINT FKOrder_part680645 FOREIGN KEY (OrderID) REFERENCES "Order" (OrderID) [42102-197]
2019-03-15 16:20:45 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "User" not found; SQL statement:
ALTER TABLE Report ADD CONSTRAINT FKReport822311 FOREIGN KEY (Username) REFERENCES "User" (Username) [42102-197]
2019-03-15 16:20:45 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Table "User" not found; SQL statement:
ALTER TABLE Mechanic ADD CONSTRAINT FKMechanic162102 FOREIGN KEY (Username) REFERENCES "User" (Username) [42102-197]
2019-03-15 17:43:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "Jimin" not found; SQL statement:
UPDATE GARAGE."User" SET PASSWORD="nohoney" WHERE USERNAME="Jimin" [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.expression.Comparison.optimize(Comparison.java:179)
	at org.h2.command.dml.Update.prepare(Update.java:216)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-15 17:45:54 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "Jimin" not found; SQL statement:
update GARAGE."User" SET PASSWORD="nohoney" WHERE USERNAME="Jimin" [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.expression.Comparison.optimize(Comparison.java:179)
	at org.h2.command.dml.Update.prepare(Update.java:216)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-15 17:47:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "Jimin" not found; SQL statement:
UPDATE GARAGE."User"
SET PASSWORD = "nohoney"
WHERE USERNAME = "Jimin" [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.expression.Comparison.optimize(Comparison.java:179)
	at org.h2.command.dml.Update.prepare(Update.java:216)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-15 17:48:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "JIMIN" not found; SQL statement:
UPDATE GARAGE."User"
SET PASSWORD = "nohoney"
WHERE USERNAME = Jimin [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.expression.Comparison.optimize(Comparison.java:179)
	at org.h2.command.dml.Update.prepare(Update.java:216)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-15 17:48:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "nohoney" not found; SQL statement:
UPDATE GARAGE."User"
SET PASSWORD = "nohoney"
WHERE USERNAME = 1 [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.command.dml.Update.prepare(Update.java:225)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-15 17:48:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "nohoney" not found; SQL statement:
UPDATE GARAGE."User"
SET PASSWORD = "nohoney" [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.command.dml.Update.prepare(Update.java:225)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-15 17:49:15 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM GARAGE.""User""UPDATE GARAGE[*].""User""
SET PASSWORD = 'nojams'
WHERE USERNAME = 'Jimin'"; SQL statement:
SELECT * FROM GARAGE."User"UPDATE GARAGE."User"
SET PASSWORD = 'nojams'
WHERE USERNAME = 'Jimin' [42000-197]
2019-03-15 17:49:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM GARAGE.""User""
SET PASSWORD[*] = 'nojams'
WHERE USERNAME = 'Jimin'"; SQL statement:
SELECT * FROM GARAGE."User"
SET PASSWORD = 'nojams'
WHERE USERNAME = 'Jimin' [42000-197]
2019-03-17 15:10:37 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:197)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:137)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 14 more
2019-03-17 16:21:54 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:197)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:137)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 14 more
2019-03-17 16:29:01 jdbc[4]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:197)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:137)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 14 more
2019-03-20 11:15:05 database: wrong user or password; user: "ROOT"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-03-20 11:16:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CUSTOMER: CUSTOMERID INT DEFAULT (NEXT VALUE FOR GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836) NOT NULL NULL_TO_DEFAULT SEQUENCE GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836)"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date")VALUES(?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10) [22018-197]
2019-03-20 11:16:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CUSTOMER: CUSTOMERID INT DEFAULT (NEXT VALUE FOR GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836) NOT NULL NULL_TO_DEFAULT SEQUENCE GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836)"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date")VALUES(?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10) [22018-197]
2019-03-20 13:42:07 database: wrong user or password; user: "ROOT"
org.h2.message.DbException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:107)
	at org.h2.engine.Engine.openSession(Engine.java:179)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:157)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 19 more
2019-03-20 13:43:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CUSTOMER: CUSTOMERID INT DEFAULT (NEXT VALUE FOR GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836) NOT NULL NULL_TO_DEFAULT SEQUENCE GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836)"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) [22018-197]
2019-03-20 13:43:21 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CUSTOMER: CUSTOMERID INT DEFAULT (NEXT VALUE FOR GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836) NOT NULL NULL_TO_DEFAULT SEQUENCE GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836)"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) [22018-197]
2019-03-20 13:45:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CUSTOMER: CUSTOMERID INT DEFAULT (NEXT VALUE FOR GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836) NOT NULL NULL_TO_DEFAULT SEQUENCE GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836)"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) [22018-197]
2019-03-20 13:45:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CUSTOMER: CUSTOMERID INT DEFAULT (NEXT VALUE FOR GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836) NOT NULL NULL_TO_DEFAULT SEQUENCE GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836)"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) [22018-197]
2019-03-20 13:46:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'07495637483' (CUSTOMER: PHONE INT)"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) [22018-197]
2019-03-20 13:46:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'07495637483' (CUSTOMER: PHONE INT)"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) [22018-197]
2019-03-20 13:48:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CUSTOMER: CUSTOMERID INT DEFAULT (NEXT VALUE FOR GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836) NOT NULL NULL_TO_DEFAULT SEQUENCE GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836)"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) [22018-197]
2019-03-20 13:48:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CUSTOMER: CUSTOMERID INT DEFAULT (NEXT VALUE FOR GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836) NOT NULL NULL_TO_DEFAULT SEQUENCE GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836)"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) [22018-197]
2019-03-20 13:49:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "DATE" constant "02/02/1999"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) [22007-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueDate.parse(ValueDate.java:74)
	at org.h2.value.Value.convertTo(Value.java:1069)
	at org.h2.table.Column.convert(Column.java:177)
	at org.h2.command.dml.Insert.insertRows(Insert.java:166)
	at org.h2.command.dml.Insert.update(Insert.java:134)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.h2.result.UpdatableRow.insertRow(UpdatableRow.java:321)
	at org.h2.jdbc.JdbcResultSet.insertRow(JdbcResultSet.java:2994)
	at org.h2.server.web.WebApp.editResult(WebApp.java:1082)
	at org.h2.server.web.WebApp.process(WebApp.java:227)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: 02/02/1999
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:345)
	at org.h2.value.ValueDate.parse(ValueDate.java:72)
	... 16 more
2019-03-20 13:49:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "DATE" constant "02/02/1999"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) [22007-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueDate.parse(ValueDate.java:74)
	at org.h2.value.Value.convertTo(Value.java:1069)
	at org.h2.table.Column.convert(Column.java:177)
	at org.h2.command.dml.Insert.insertRows(Insert.java:166)
	at org.h2.command.dml.Insert.update(Insert.java:134)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.h2.result.UpdatableRow.insertRow(UpdatableRow.java:321)
	at org.h2.jdbc.JdbcResultSet.insertRow(JdbcResultSet.java:2994)
	at org.h2.server.web.WebApp.editResult(WebApp.java:1082)
	at org.h2.server.web.WebApp.process(WebApp.java:227)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: 02/02/1999
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:345)
	at org.h2.value.ValueDate.parse(ValueDate.java:72)
	... 16 more
2019-03-20 13:49:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "DATE" constant "1990/02/10"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) [22007-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueDate.parse(ValueDate.java:74)
	at org.h2.value.Value.convertTo(Value.java:1069)
	at org.h2.table.Column.convert(Column.java:177)
	at org.h2.command.dml.Insert.insertRows(Insert.java:166)
	at org.h2.command.dml.Insert.update(Insert.java:134)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.h2.result.UpdatableRow.insertRow(UpdatableRow.java:321)
	at org.h2.jdbc.JdbcResultSet.insertRow(JdbcResultSet.java:2994)
	at org.h2.server.web.WebApp.editResult(WebApp.java:1082)
	at org.h2.server.web.WebApp.process(WebApp.java:227)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: 1990/02/10
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:345)
	at org.h2.value.ValueDate.parse(ValueDate.java:72)
	... 16 more
2019-03-20 13:49:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "DATE" constant "1990/02/10"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) [22007-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueDate.parse(ValueDate.java:74)
	at org.h2.value.Value.convertTo(Value.java:1069)
	at org.h2.table.Column.convert(Column.java:177)
	at org.h2.command.dml.Insert.insertRows(Insert.java:166)
	at org.h2.command.dml.Insert.update(Insert.java:134)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:199)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:153)
	at org.h2.result.UpdatableRow.insertRow(UpdatableRow.java:321)
	at org.h2.jdbc.JdbcResultSet.insertRow(JdbcResultSet.java:2994)
	at org.h2.server.web.WebApp.editResult(WebApp.java:1082)
	at org.h2.server.web.WebApp.process(WebApp.java:227)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: 1990/02/10
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:345)
	at org.h2.value.ValueDate.parse(ValueDate.java:72)
	... 16 more
2019-03-20 13:52:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CUSTOMER: CUSTOMERID INT DEFAULT (NEXT VALUE FOR GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836) NOT NULL NULL_TO_DEFAULT SEQUENCE GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836)"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) [22018-197]
2019-03-20 13:52:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CUSTOMER: CUSTOMERID INT DEFAULT (NEXT VALUE FOR GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836) NOT NULL NULL_TO_DEFAULT SEQUENCE GARAGE.SYSTEM_SEQUENCE_5722893F_6DCD_41F0_9D44_41444C53D836)"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) [22018-197]
2019-03-20 13:55:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CUSTOMER: CUSTOMERID INT DEFAULT (NEXT VALUE FOR GARAGE.SYSTEM_SEQUENCE_B00956C2_8FDC_495A_9B2C_3BE72B925D72) NOT NULL NULL_TO_DEFAULT SEQUENCE GARAGE.SYSTEM_SEQUENCE_B00956C2_8FDC_495A_9B2C_3BE72B925D72)"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) [22018-197]
2019-03-20 13:55:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CUSTOMER: CUSTOMERID INT DEFAULT (NEXT VALUE FOR GARAGE.SYSTEM_SEQUENCE_B00956C2_8FDC_495A_9B2C_3BE72B925D72) NOT NULL NULL_TO_DEFAULT SEQUENCE GARAGE.SYSTEM_SEQUENCE_B00956C2_8FDC_495A_9B2C_3BE72B925D72)"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","CITY","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) [22018-197]
2019-03-20 13:58:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "DATE" not found; SQL statement:
INSERT INTO GARAGE.CUSTOMER (FIRSTNAME, LASTNAME, TYPE, ADDRESS, POSTCODE, CITY, PHONE, EMAIL, Date, LATEPAYMENT)
VALUES ('Donald', 'Duck', 'ACCOUNT', '12 Yep Street', 'SW15 0AD', 'London'. '05689765451', 'what@evermail.com', '1989-28-01', 'TRUE') [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.parseColumn(Parser.java:936)
	at org.h2.command.Parser.parseColumnList(Parser.java:920)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1258)
	at org.h2.command.Parser.parseInsert(Parser.java:1222)
	at org.h2.command.Parser.parsePrepared(Parser.java:431)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-20 13:58:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO GARAGE.CUSTOMER (FIRSTNAME, LASTNAME, TYPE, ADDRESS, POSTCODE, CITY, PHONE, EMAIL, ""Date"", LATEPAYMENT)
VALUES ('Donald', 'Duck', 'ACCOUNT', '12 Yep Street', 'SW15 0AD', 'London'.[*] '05689765451', 'what@evermail.com', '1989-28-01', 'TRUE')"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO GARAGE.CUSTOMER (FIRSTNAME, LASTNAME, TYPE, ADDRESS, POSTCODE, CITY, PHONE, EMAIL, "Date", LATEPAYMENT)
VALUES ('Donald', 'Duck', 'ACCOUNT', '12 Yep Street', 'SW15 0AD', 'London'. '05689765451', 'what@evermail.com', '1989-28-01', 'TRUE') [42001-197]
2019-03-20 13:59:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "DATE" constant "1989-28-01"; SQL statement:
INSERT INTO GARAGE.CUSTOMER (FIRSTNAME, LASTNAME, TYPE, ADDRESS, POSTCODE, CITY, PHONE, EMAIL, "Date", LATEPAYMENT)
VALUES ('Donald', 'Duck', 'ACCOUNT', '12 Yep Street', 'SW15 0AD', 'London', '05689765451', 'what@evermail.com', '1989-28-01', 'TRUE') -- ('Donald', 'Duck', 'ACCOUNT', '12 Yep Street', 'SW15 0AD', 'London', '05689765451', 'what@evermail.com', '1989-28-01', 'TRUE') [22007-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueDate.parse(ValueDate.java:74)
	at org.h2.value.Value.convertTo(Value.java:1069)
	at org.h2.table.Column.convert(Column.java:177)
	at org.h2.command.dml.Insert.insertRows(Insert.java:166)
	at org.h2.command.dml.Insert.update(Insert.java:134)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: 1989-28-1
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:351)
	at org.h2.value.ValueDate.parse(ValueDate.java:72)
	... 15 more
2019-03-20 14:00:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "DATE" constant "1960"; SQL statement:
INSERT INTO GARAGE.CUSTOMER (FIRSTNAME, LASTNAME, TYPE, ADDRESS, POSTCODE, CITY, PHONE, EMAIL, "Date", LATEPAYMENT)
VALUES ('Donald', 'Duck', 'ACCOUNT', '12 Yep Street', 'SW15 0AD', 'London', '05689765451', 'what@evermail.com', 1989-28-01, 'TRUE') -- ('Donald', 'Duck', 'ACCOUNT', '12 Yep Street', 'SW15 0AD', 'London', '05689765451', 'what@evermail.com', 1960, 'TRUE') [22007-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueDate.parse(ValueDate.java:74)
	at org.h2.value.Value.convertTo(Value.java:1069)
	at org.h2.table.Column.convert(Column.java:177)
	at org.h2.command.dml.Insert.insertRows(Insert.java:166)
	at org.h2.command.dml.Insert.update(Insert.java:134)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: 1960
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:345)
	at org.h2.value.ValueDate.parse(ValueDate.java:72)
	... 15 more
2019-03-20 14:00:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "1989-28-01" not found; SQL statement:
INSERT INTO GARAGE.CUSTOMER (FIRSTNAME, LASTNAME, TYPE, ADDRESS, POSTCODE, CITY, PHONE, EMAIL, "Date", LATEPAYMENT)
VALUES ('Donald', 'Duck', 'ACCOUNT', '12 Yep Street', 'SW15 0AD', 'London', '05689765451', 'what@evermail.com', "1989-28-01", 'TRUE') [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.command.dml.Insert.prepare(Insert.java:314)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-20 14:00:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "DATE" not found; SQL statement:
INSERT INTO GARAGE.CUSTOMER (FIRSTNAME, LASTNAME, TYPE, ADDRESS, POSTCODE, CITY, PHONE, EMAIL, Date, LATEPAYMENT)
VALUES ('Donald', 'Duck', 'ACCOUNT', '12 Yep Street', 'SW15 0AD', 'London', '05689765451', 'what@evermail.com', "1989-28-01", 'TRUE') [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.parseColumn(Parser.java:936)
	at org.h2.command.Parser.parseColumnList(Parser.java:920)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1258)
	at org.h2.command.Parser.parseInsert(Parser.java:1222)
	at org.h2.command.Parser.parsePrepared(Parser.java:431)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-20 14:00:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO GARAGE.CUSTOMER (FIRSTNAME, LASTNAME, TYPE, ADDRESS, POSTCODE, CITY, PHONE, EMAIL, 'Date'[*], LATEPAYMENT)
VALUES ('Donald', 'Duck', 'ACCOUNT', '12 Yep Street', 'SW15 0AD', 'London', '05689765451', 'what@evermail.com', ""1989-28-01"", 'TRUE')"; expected "identifier"; SQL statement:
INSERT INTO GARAGE.CUSTOMER (FIRSTNAME, LASTNAME, TYPE, ADDRESS, POSTCODE, CITY, PHONE, EMAIL, 'Date', LATEPAYMENT)
VALUES ('Donald', 'Duck', 'ACCOUNT', '12 Yep Street', 'SW15 0AD', 'London', '05689765451', 'what@evermail.com', "1989-28-01", 'TRUE') [42001-197]
2019-03-20 14:00:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "1989-28-01" not found; SQL statement:
INSERT INTO GARAGE.CUSTOMER (FIRSTNAME, LASTNAME, TYPE, ADDRESS, POSTCODE, CITY, PHONE, EMAIL, "Date", LATEPAYMENT)
VALUES ('Donald', 'Duck', 'ACCOUNT', '12 Yep Street', 'SW15 0AD', 'London', '05689765451', 'what@evermail.com', "1989-28-01", 'TRUE') [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.command.dml.Insert.prepare(Insert.java:314)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-20 14:01:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO GARAGE.CUSTOMER (FIRSTNAME, LASTNAME, TYPE, ADDRESS, POSTCODE, CITY, PHONE, EMAIL, ""Date"", LATEPAYMENT)
VALUES ('Donald', 'Duck', 'ACCOUNT', '12 Yep Street', 'SW15 0AD', 'London', '05689765451', 'what@evermail.com', 1989-08-01[*]"", 'TRUE')"; SQL statement:
INSERT INTO GARAGE.CUSTOMER (FIRSTNAME, LASTNAME, TYPE, ADDRESS, POSTCODE, CITY, PHONE, EMAIL, "Date", LATEPAYMENT)
VALUES ('Donald', 'Duck', 'ACCOUNT', '12 Yep Street', 'SW15 0AD', 'London', '05689765451', 'what@evermail.com', 1989-08-01", 'TRUE') [42000-197]
2019-03-20 14:01:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "DATE" constant "1980"; SQL statement:
INSERT INTO GARAGE.CUSTOMER (FIRSTNAME, LASTNAME, TYPE, ADDRESS, POSTCODE, CITY, PHONE, EMAIL, "Date", LATEPAYMENT)
VALUES ('Donald', 'Duck', 'ACCOUNT', '12 Yep Street', 'SW15 0AD', 'London', '05689765451', 'what@evermail.com', 1989-08-01, 'TRUE') -- ('Donald', 'Duck', 'ACCOUNT', '12 Yep Street', 'SW15 0AD', 'London', '05689765451', 'what@evermail.com', 1980, 'TRUE') [22007-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueDate.parse(ValueDate.java:74)
	at org.h2.value.Value.convertTo(Value.java:1069)
	at org.h2.table.Column.convert(Column.java:177)
	at org.h2.command.dml.Insert.insertRows(Insert.java:166)
	at org.h2.command.dml.Insert.update(Insert.java:134)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: 1980
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:345)
	at org.h2.value.ValueDate.parse(ValueDate.java:72)
	... 15 more
2019-03-20 14:27:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "ENDSERIAL" not found; SQL statement:
INSERT INTO GARAGE.CAR (CUSTOMERID, MANUFACTURERID, MAKE, MODEL, ENDSERIAL, CHASSISNUMBER, COLOUR)
VALUES('1', '1', 'Car', 'AD123', '00291', 'Blue') [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.parseColumn(Parser.java:936)
	at org.h2.command.Parser.parseColumnList(Parser.java:920)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1258)
	at org.h2.command.Parser.parseInsert(Parser.java:1222)
	at org.h2.command.Parser.parsePrepared(Parser.java:431)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-20 14:28:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
INSERT INTO GARAGE.CAR (CUSTOMERID, MANUFACTURERID, MAKE, MODEL, ENGSERIAL, CHASSISNUMBER, COLOUR)
VALUES('1', '1', 'Car', 'AD123', '00291', 'Blue') [21002-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:306)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-20 14:29:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "COMPANYADDRESS"; SQL statement:
ALTER TABLE GARAGE.MANUFACTURER
MODIFY COMPANYADRESS COMPANYADDRESS VARCHAR(100) [50004-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4400)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4215)
	at org.h2.command.Parser.parseAlterTableAlterColumnType(Parser.java:6296)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6146)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-20 14:29:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "COMPANYADDRESS"; SQL statement:
ALTER TABLE GARAGE.MANUFACTURER
MODIFY COLUMN COMPANYADRESS COMPANYADDRESS VARCHAR(100) [50004-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4400)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4215)
	at org.h2.command.Parser.parseAlterTableAlterColumnType(Parser.java:6296)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6146)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-20 14:31:55 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'05678461548' (MANUFACTURER: PHONE INT)"; SQL statement:
INSERT INTO GARAGE.MANUFACTURER (COMPANYNAME, COMPANYADDRESS, PHONE, FAX)
VALUES ('Twins Company Inc', '12 Seattle Way', '05678461548', '789895') -- ('Twins Company Inc', '12 Seattle Way', '05678461548', '789895') [22018-197]
2019-03-20 14:34:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement:
INSERT INTO GARAGE.CAR (CUSTOMERID, MANUFACTURERID, MAKE, MODEL, ENGSERIAL, CHASSISNUMBER, COLOUR)
VALUES('1', '1', 'Car', 'AD123', '00291', 'Blue') [21002-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Insert.prepare(Insert.java:306)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-20 14:35:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "PRIMARY"; SQL statement:
ALTER TABLE GARAGE.CAR
MODIFY REGISTRATIONID PRIMARY KEY NOT NULL Auto_Increment [50004-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4400)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4215)
	at org.h2.command.Parser.parseAlterTableAlterColumnType(Parser.java:6296)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6146)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-20 14:35:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "PRIMARYKEY"; SQL statement:
ALTER TABLE GARAGE.CAR
MODIFY REGISTRATIONID PRIMARYKEY NOT NULL Auto_Increment [50004-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4400)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4215)
	at org.h2.command.Parser.parseAlterTableAlterColumnType(Parser.java:6296)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6146)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-20 14:35:35 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.CAR
MODIFY REGISTRATIONID NOT NULL AUTO_INCREMENT[*] "; SQL statement:
ALTER TABLE GARAGE.CAR
MODIFY REGISTRATIONID NOT NULL Auto_Increment [42000-197]
2019-03-20 14:35:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.CAR
MODIFY REGISTRATIONID INT PRIMARYKEY[*] NOT NULL AUTO_INCREMENT "; SQL statement:
ALTER TABLE GARAGE.CAR
MODIFY REGISTRATIONID int PRIMARYKEY NOT NULL Auto_Increment [42000-197]
2019-03-20 14:35:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.CAR
MODIFY REGISTRATIONID INT PRIMARY[*] KEY NOT NULL AUTO_INCREMENT "; SQL statement:
ALTER TABLE GARAGE.CAR
MODIFY REGISTRATIONID int PRIMARY KEY NOT NULL Auto_Increment [42000-197]
2019-03-20 14:37:36 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO GARAGE.CAR (CUSTOMERID, MANUFACTURERID, MAKE, MODEL, ENGSERIAL, CHASSISNUMBER, COLOUR)
VALUES('1', '2', 'Car, 'BA457[*], 'AB784', '01351', 'Red')"; expected "[, ::, *, /, %, +, -, ||, ~, !~, NOT, LIKE, ILIKE, REGEXP, IS, IN, BETWEEN, AND, OR, ,, )"; SQL statement:
INSERT INTO GARAGE.CAR (CUSTOMERID, MANUFACTURERID, MAKE, MODEL, ENGSERIAL, CHASSISNUMBER, COLOUR)
VALUES('1', '2', 'Car, 'BA457, 'AB784', '01351', 'Red') [42001-197]
2019-03-20 14:37:53 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO GARAGE.CAR (CUSTOMERID, MANUFACTURERID, MAKE, MODEL, ENGSERIAL, CHASSISNUMBER, COLOUR)
VALUES('1', '2', 'Car', 'BA457, 'AB784', '01351', 'Red[*]')"; SQL statement:
INSERT INTO GARAGE.CAR (CUSTOMERID, MANUFACTURERID, MAKE, MODEL, ENGSERIAL, CHASSISNUMBER, COLOUR)
VALUES('1', '2', 'Car', 'BA457, 'AB784', '01351', 'Red') [42000-197]
2019-03-20 22:38:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CAR: CUSTOMERID INT NOT NULL)"; SQL statement:
UPDATE "GARAGE"."CAR" SET "REGISTRATIONID"=? ,"CUSTOMERID"=? ,"MANUFACTURERID"=? ,"MAKE"=? ,"MODEL"=? ,"ENGSERIAL"=? ,"CHASSISNUMBER"=? ,"COLOUR"=?  WHERE "REGISTRATIONID"=? [22018-197]
2019-03-20 22:38:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CAR: CUSTOMERID INT NOT NULL)"; SQL statement:
UPDATE "GARAGE"."CAR" SET "REGISTRATIONID"=? ,"CUSTOMERID"=? ,"MANUFACTURERID"=? ,"MAKE"=? ,"MODEL"=? ,"ENGSERIAL"=? ,"CHASSISNUMBER"=? ,"COLOUR"=?  WHERE "REGISTRATIONID"=? [22018-197]
2019-03-20 22:38:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CAR: CUSTOMERID INT NOT NULL)"; SQL statement:
UPDATE "GARAGE"."CAR" SET "REGISTRATIONID"=? ,"CUSTOMERID"=? ,"MANUFACTURERID"=? ,"MAKE"=? ,"MODEL"=? ,"ENGSERIAL"=? ,"CHASSISNUMBER"=? ,"COLOUR"=?  WHERE "REGISTRATIONID"=? [22018-197]
2019-03-20 22:38:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CAR: CUSTOMERID INT NOT NULL)"; SQL statement:
UPDATE "GARAGE"."CAR" SET "REGISTRATIONID"=? ,"CUSTOMERID"=? ,"MANUFACTURERID"=? ,"MAKE"=? ,"MODEL"=? ,"ENGSERIAL"=? ,"CHASSISNUMBER"=? ,"COLOUR"=?  WHERE "REGISTRATIONID"=? [22018-197]
2019-03-20 22:40:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CAR: CUSTOMERID INT NOT NULL)"; SQL statement:
INSERT INTO "GARAGE"."CAR"("REGISTRATIONID","CUSTOMERID","MANUFACTURERID","MAKE","MODEL","ENGSERIAL","CHASSISNUMBER","COLOUR")VALUES(?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8) [22018-197]
2019-03-20 22:40:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CAR: CUSTOMERID INT NOT NULL)"; SQL statement:
INSERT INTO "GARAGE"."CAR"("REGISTRATIONID","CUSTOMERID","MANUFACTURERID","MAKE","MODEL","ENGSERIAL","CHASSISNUMBER","COLOUR")VALUES(?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8) [22018-197]
2019-03-20 22:41:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CAR: CUSTOMERID INT NOT NULL)"; SQL statement:
UPDATE "GARAGE"."CAR" SET "REGISTRATIONID"=? ,"CUSTOMERID"=? ,"MANUFACTURERID"=? ,"MAKE"=? ,"MODEL"=? ,"ENGSERIAL"=? ,"CHASSISNUMBER"=? ,"COLOUR"=?  WHERE "REGISTRATIONID"=? [22018-197]
2019-03-20 22:41:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CAR: CUSTOMERID INT NOT NULL)"; SQL statement:
UPDATE "GARAGE"."CAR" SET "REGISTRATIONID"=? ,"CUSTOMERID"=? ,"MANUFACTURERID"=? ,"MAKE"=? ,"MODEL"=? ,"ENGSERIAL"=? ,"CHASSISNUMBER"=? ,"COLOUR"=?  WHERE "REGISTRATIONID"=? [22018-197]
2019-03-20 22:42:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CAR: CUSTOMERID INT)"; SQL statement:
UPDATE "GARAGE"."CAR" SET "REGISTRATIONID"=? ,"CUSTOMERID"=? ,"MANUFACTURERID"=? ,"MAKE"=? ,"MODEL"=? ,"ENGSERIAL"=? ,"CHASSISNUMBER"=? ,"COLOUR"=?  WHERE "REGISTRATIONID"=? [22018-197]
2019-03-20 22:42:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CAR: CUSTOMERID INT)"; SQL statement:
UPDATE "GARAGE"."CAR" SET "REGISTRATIONID"=? ,"CUSTOMERID"=? ,"MANUFACTURERID"=? ,"MAKE"=? ,"MODEL"=? ,"ENGSERIAL"=? ,"CHASSISNUMBER"=? ,"COLOUR"=?  WHERE "REGISTRATIONID"=? [22018-197]
2019-03-20 22:43:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "MANUFACTUREID" not found; SQL statement:
INSERT INTO GARAGE.CAR (MANUFACTUREID, MAKE, MODEL, ENGSERIAL, CHASSISNUMBER, COLOUR)
VALUES (1, 'Car', 'AB093', 'AK093', '00392', 'Purple') [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.parseColumn(Parser.java:936)
	at org.h2.command.Parser.parseColumnList(Parser.java:920)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1258)
	at org.h2.command.Parser.parseInsert(Parser.java:1222)
	at org.h2.command.Parser.parsePrepared(Parser.java:431)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-20 22:43:43 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "MANUFACTUREREID" not found; SQL statement:
INSERT INTO GARAGE.CAR (MANUFACTUREREID, MAKE, MODEL, ENGSERIAL, CHASSISNUMBER, COLOUR)
VALUES (1, 'Car', 'AB093', 'AK093', '00392', 'Purple') [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.parseColumn(Parser.java:936)
	at org.h2.command.Parser.parseColumnList(Parser.java:920)
	at org.h2.command.Parser.parseInsertGivenTable(Parser.java:1258)
	at org.h2.command.Parser.parseInsert(Parser.java:1222)
	at org.h2.command.Parser.parsePrepared(Parser.java:431)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-21 10:45:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "COLOUMN" not found; SQL statement:
ALTER TABLE GARAGE.CUSTOMER
DROP COLOUMN CITY [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6088)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-21 10:45:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "COLOUMN" not found; SQL statement:
ALTER TABLE GARAGE.CUSTOMER
DROP COLOUMN CITY [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6088)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-21 12:09:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CUSTOMER: CUSTOMERID INT DEFAULT (NEXT VALUE FOR GARAGE.SYSTEM_SEQUENCE_B00956C2_8FDC_495A_9B2C_3BE72B925D72) NOT NULL NULL_TO_DEFAULT SEQUENCE GARAGE.SYSTEM_SEQUENCE_B00956C2_8FDC_495A_9B2C_3BE72B925D72)"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10) [22018-197]
2019-03-21 12:09:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'' (CUSTOMER: CUSTOMERID INT DEFAULT (NEXT VALUE FOR GARAGE.SYSTEM_SEQUENCE_B00956C2_8FDC_495A_9B2C_3BE72B925D72) NOT NULL NULL_TO_DEFAULT SEQUENCE GARAGE.SYSTEM_SEQUENCE_B00956C2_8FDC_495A_9B2C_3BE72B925D72)"; SQL statement:
INSERT INTO "GARAGE"."CUSTOMER"("CUSTOMERID","FIRSTNAME","LASTNAME","TYPE","ADDRESS","POSTCODE","PHONE","EMAIL","Date","LATEPAYMENT")VALUES(?,?,?,?,?,?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10) [22018-197]
2019-03-21 22:30:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "SCOPE_IDENTITY" not found; SQL statement:
Select scope_identity [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.command.dml.Select.prepare(Select.java:858)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-21 22:33:59 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "1992-02-19" not found; SQL statement:
insert into GARAGE.CUSTOMER (FIRSTNAME, LASTNAME, TYPE, ADDRESS, POSTCODE, PHONE, EMAIL, "Date", LATEPAYMENT)
values ('assa', 'asas', 'asas', 'asas', 'asasas','sasdasdas', 'adasds', "1992-02-19", TRUE) [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.command.dml.Insert.prepare(Insert.java:314)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-21 22:34:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Cannot parse "DATE" constant "1971"; SQL statement:
insert into GARAGE.CUSTOMER (FIRSTNAME, LASTNAME, TYPE, ADDRESS, POSTCODE, PHONE, EMAIL, "Date", LATEPAYMENT)
values ('assa', 'asas', 'asas', 'asas', 'asasas','sasdasdas', 'adasds', 1992-02-19, TRUE) -- ('assa', 'asas', 'asas', 'asas', 'asasas', 'sasdasdas', 'adasds', 1971, TRUE) [22007-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.value.ValueDate.parse(ValueDate.java:74)
	at org.h2.value.Value.convertTo(Value.java:1069)
	at org.h2.table.Column.convert(Column.java:177)
	at org.h2.command.dml.Insert.insertRows(Insert.java:166)
	at org.h2.command.dml.Insert.update(Insert.java:134)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: 1971
	at org.h2.util.DateTimeUtils.parseDateValue(DateTimeUtils.java:345)
	at org.h2.value.ValueDate.parse(ValueDate.java:72)
	... 15 more
2019-03-21 23:19:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "COUNT" not found; SQL statement:
SELECT COUNT FROM GARAGE.CUSTOMER [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.command.dml.Select.prepare(Select.java:858)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-21 23:19:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT COUNT()[*] FROM GARAGE.CUSTOMER"; expected "*, DISTINCT, NOT, EXISTS, INTERSECTS"; SQL statement:
SELECT COUNT() FROM GARAGE.CUSTOMER [42001-197]
2019-03-21 23:34:16 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.CUSTOMER 
AUTO_INCREMENT[*]=10"; expected "ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
ALTER TABLE GARAGE.CUSTOMER 
AUTO_INCREMENT=10 [42001-197]
2019-03-21 23:35:10 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.CUSTOMER 
AUTO_INCREMENT[*]=9"; expected "ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
ALTER TABLE GARAGE.CUSTOMER 
AUTO_INCREMENT=9 [42001-197]
2019-03-21 23:35:18 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.CUSTOMER 
AUTO_INCREMENT[*] = 9"; expected "ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
ALTER TABLE GARAGE.CUSTOMER 
AUTO_INCREMENT = 9 [42001-197]
2019-03-21 23:35:32 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Column "AUTO_INCREMENT" not found; SQL statement:
ALTER TABLE GARAGE.CUSTOMER 
MODIFY
AUTO_INCREMENT = 9 [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.columnIfTableExists(Parser.java:6283)
	at org.h2.command.Parser.parseAlterTableAlterColumnType(Parser.java:6295)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6146)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-21 23:35:39 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.CUSTOMER 
AUTO_INCREMENT[*] = 9"; expected "ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
ALTER TABLE GARAGE.CUSTOMER 
AUTO_INCREMENT = 9 [42001-197]
2019-03-21 23:36:12 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.CUSTOMER AUTO_INCREMENT[*] = 9"; expected "ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
ALTER TABLE GARAGE.CUSTOMER AUTO_INCREMENT = 9 [42001-197]
2019-03-21 23:36:17 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER GARAGE[*].CUSTOMER AUTO_INCREMENT = 9"; expected "TABLE, USER, INDEX, SCHEMA, SEQUENCE, VIEW"; SQL statement:
ALTER GARAGE.CUSTOMER AUTO_INCREMENT = 9 [42001-197]
2019-03-21 23:36:38 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.CUSTOMER AUTO_INCREMENT[*] = 10 "; expected "ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
alter table GARAGE.CUSTOMER auto_increment = 10 [42001-197]
2019-03-21 23:36:45 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.CUSTOMER SET AUTO_INCREMENT[*] = 10 "; expected "REFERENTIAL_INTEGRITY"; SQL statement:
alter table GARAGE.CUSTOMER set auto_increment = 10 [42001-197]
2019-03-21 23:37:39 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DBCC[*]"; expected "DELETE, DROP, DECLARE, DEALLOCATE, {"; SQL statement:
DBCC [42001-197]
2019-03-21 23:38:21 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "DBCC[*] CHECKIDENT(GARAGE.CUSTOMER,RESEED,10) "; expected "DELETE, DROP, DECLARE, DEALLOCATE, {"; SQL statement:
dbcc checkident(GARAGE.CUSTOMER,reseed,10) [42001-197]
2019-03-21 23:39:10 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.CUSTOMER AUTO_INCREMENT[*] = 1"; expected "ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
ALTER TABLE GARAGE.CUSTOMER AUTO_INCREMENT = 1 [42001-197]
2019-03-21 23:39:13 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.CUSTOMER AUTO_INCREMENT[*] = 9"; expected "ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
ALTER TABLE GARAGE.CUSTOMER AUTO_INCREMENT = 9 [42001-197]
2019-03-21 23:39:22 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Column "AUTO_INCREMENT" not found; SQL statement:
ALTER TABLE GARAGE.CUSTOMER ALTER AUTO_INCREMENT = 9 [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.columnIfTableExists(Parser.java:6283)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6159)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-21 23:39:46 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.CUSTOMER MODIFY CUSTOMERID INT AUTO_INCREMENT =[*] 9 "; SQL statement:
ALTER TABLE GARAGE.CUSTOMER MODIFY CUSTOMERID int AUTO_INCREMENT = 9 [42000-197]
2019-03-21 23:40:05 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.CUSTOMER AUTO_INCREMENT[*] = 9"; expected "ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
ALTER TABLE GARAGE.CUSTOMER AUTO_INCREMENT = 9 [42001-197]
2019-03-21 23:40:22 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Cannot truncate "GARAGE.CUSTOMER"; SQL statement:
TRUNCATE TABLE GARAGE.CUSTOMER [90106-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.TruncateTable.update(TruncateTable.java:35)
	at org.h2.command.CommandContainer.update(CommandContainer.java:102)
	at org.h2.command.Command.executeUpdate(Command.java:261)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:233)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-21 23:41:18 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.CUSTOMER AUTO_INCREMENT[*] = 10"; expected "ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
ALTER TABLE GARAGE.CUSTOMER AUTO_INCREMENT = 10 [42001-197]
2019-03-25 14:40:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PART_JOB" not found; SQL statement:
ALTER TABLE Part_Job ADD CONSTRAINT FKPart_Job26488 FOREIGN KEY (PartPartID) REFERENCES Part (PartID) [42102-197]
2019-03-25 14:40:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Table "PART_JOB" not found; SQL statement:
ALTER TABLE Part_Job ADD CONSTRAINT FKPart_Job968051 FOREIGN KEY (JobJobID) REFERENCES Job (JobID) [42102-197]
2019-03-25 14:41:45 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "CARREGISTRATIONID"; SQL statement:
ALTER TABLE GARAGE.JOB MODIFY CARREGISTRATIOTIONID  CARREGISTRATIONID int [50004-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4400)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4215)
	at org.h2.command.Parser.parseAlterTableAlterColumnType(Parser.java:6296)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6146)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-25 14:41:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "CARREGISTRATIONID"; SQL statement:
ALTER TABLE GARAGE.JOB MODIFY Column CARREGISTRATIOTIONID  CARREGISTRATIONID int [50004-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4400)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4215)
	at org.h2.command.Parser.parseAlterTableAlterColumnType(Parser.java:6296)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6146)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-03-25 14:54:58 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.JOB CARREGISTRATIOTIONID[*]  CARREGISTRATIONID INT "; expected "ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
ALTER TABLE GARAGE.JOB CARREGISTRATIOTIONID  CARREGISTRATIONID int [42001-197]
2019-03-27 13:40:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.VEHICLE 
REMOVE[*] COLUMN MAKE"; expected "ADD, SET, RENAME, DROP, CHANGE, MODIFY, ALTER"; SQL statement:
ALTER TABLE GARAGE.VEHICLE 
REMOVE COLUMN MAKE [42001-197]
2019-03-27 13:42:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.VEHICLE 
RENAME MODEL[*] TO NAME"; expected "COLUMN, CONSTRAINT, TO"; SQL statement:
ALTER TABLE GARAGE.VEHICLE 
RENAME MODEL TO NAME [42001-197]
2019-03-27 13:42:47 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "NAME"; SQL statement:
ALTER TABLE GARAGE.VEHICLE 
CHANGE MODEL TO NAME [50004-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4400)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4215)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6116)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
2019-03-27 13:42:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "NAME"; SQL statement:
ALTER TABLE GARAGE.VEHICLE 
CHANGE MODEL TO NAME varchar [50004-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4400)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4215)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6116)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
2019-03-27 13:51:39 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "THRESOLD_LEVEL" not found; SQL statement:
ALTER TABLE GARAGE.VEHICLE 
DROP COLUMN THRESOLD_LEVEL [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Table.getColumn(Table.java:682)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6088)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
2019-03-27 14:02:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "SCHEMA" not found; SQL statement:
SELECT SCHEMA GARAGE [42122-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:150)
	at org.h2.expression.Alias.optimize(Alias.java:51)
	at org.h2.command.dml.Select.prepare(Select.java:858)
	at org.h2.command.Parser.prepareCommand(Parser.java:283)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
2019-03-27 14:02:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SET DEFAULT[*] SCHEMA GARAGE"; expected "@, AUTOCOMMIT, MVCC, EXCLUSIVE, IGNORECASE, PASSWORD, SALT, MODE, COMPRESS_LOB, DATABASE, COLLATION, BINARY_COLLATION, CLUSTER, DATABASE_EVENT_LISTENER, ALLOW_LITERALS, DEFAULT_TABLE_TYPE, CREATE, HSQLDB.DEFAULT_TABLE_TYPE, PAGE_STORE, CACHE_TYPE, FILE_LOCK, DB_CLOSE_ON_EXIT, AUTO_SERVER, AUTO_SERVER_PORT, AUTO_RECONNECT, ASSERT, ACCESS_MODE_DATA, OPEN_NEW, JMX, PAGE_SIZE, RECOVER, NAMES, SCOPE_GENERATED_KEYS, SCHEMA, DATESTYLE, SEARCH_PATH, SCHEMA_SEARCH_PATH, JAVA_OBJECT_SERIALIZER, LOGSIZE, FOREIGN_KEY_CHECKS"; SQL statement:
SET DEFAULT SCHEMA GARAGE [42001-197]
2019-03-27 14:02:40 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SET DEFAULT[*] GARAGE"; expected "@, AUTOCOMMIT, MVCC, EXCLUSIVE, IGNORECASE, PASSWORD, SALT, MODE, COMPRESS_LOB, DATABASE, COLLATION, BINARY_COLLATION, CLUSTER, DATABASE_EVENT_LISTENER, ALLOW_LITERALS, DEFAULT_TABLE_TYPE, CREATE, HSQLDB.DEFAULT_TABLE_TYPE, PAGE_STORE, CACHE_TYPE, FILE_LOCK, DB_CLOSE_ON_EXIT, AUTO_SERVER, AUTO_SERVER_PORT, AUTO_RECONNECT, ASSERT, ACCESS_MODE_DATA, OPEN_NEW, JMX, PAGE_SIZE, RECOVER, NAMES, SCOPE_GENERATED_KEYS, SCHEMA, DATESTYLE, SEARCH_PATH, SCHEMA_SEARCH_PATH, JAVA_OBJECT_SERIALIZER, LOGSIZE, FOREIGN_KEY_CHECKS"; SQL statement:
SET DEFAULT GARAGE [42001-197]
2019-03-27 14:51:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "ID"; SQL statement:
ALTER TABLE GARAGE.NOTIFICATION
ADD NOTIFICATION ID int Not_Null Auto_Increment [50004-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4400)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4215)
	at org.h2.command.Parser.parseTableColumnDefinition(Parser.java:6662)
	at org.h2.command.Parser.parseAlterTableAddColumn(Parser.java:6324)
	at org.h2.command.Parser.parseAlterTable(Parser.java:5983)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
2019-03-27 14:51:56 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "ALTER TABLE GARAGE.NOTIFICATION
ADD ID INT NOT_NULL[*] AUTO_INCREMENT "; SQL statement:
ALTER TABLE GARAGE.NOTIFICATION
ADD ID int Not_Null Auto_Increment [42000-197]
2019-03-27 16:47:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: ; SQL statement:
ALTER TABLE GARAGE.NOTIFICATION
CHANGE PERIOD DATETIME [50004-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4400)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4215)
	at org.h2.command.Parser.parseAlterTable(Parser.java:6116)
	at org.h2.command.Parser.parseAlter(Parser.java:5373)
	at org.h2.command.Parser.parsePrepared(Parser.java:362)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:217)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:1077)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1386)
	at org.h2.server.web.WebApp.query(WebApp.java:1060)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1022)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1009)
	at org.h2.server.web.WebThread.process(WebThread.java:165)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.lang.Thread.run(Thread.java:748)
2019-03-27 18:38:52 jdbc[5]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:197)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:137)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:733)
	at org.h2.server.web.WebApp.login(WebApp.java:954)
	at org.h2.server.web.WebApp.process(WebApp.java:211)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:170)
	at org.h2.server.web.WebThread.process(WebThread.java:134)
	at org.h2.server.web.WebThread.run(WebThread.java:90)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 14 more
2019-03-28 12:17:04 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "GARAGE[*].MECHANIC"; expected "GRANT, {"; SQL statement:
GARAGE.MECHANIC [42001-197]
